programme : main_list.o list.o testListHelpers.o 
	gcc -o programme main_list.o list.o testListHelpers.o -g
main_list.o : main_list.c 
	gcc -c main_list.c -o main_list.o -g
list.o : list.c
	gcc -c list.c -o list.o -g
testListHelpers.o : testListHelpers.c 
	gcc -c testListHelpers.c -o testListHelpers.o -g
